# Generated by Django 5.0.3 on 2024-03-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_label_dataset_label_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='img',
            field=models.URLField(null=True),
        ),
    ]
