# Generated by Django 5.0.3 on 2024-03-20 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_dataset_img_alter_dataset_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.label')),
            ],
        ),
    ]
