# Generated by Django 3.2.25 on 2024-04-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_dataset_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='img',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='img',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
