# Generated by Django 3.2.25 on 2024-04-03 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20240402_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='img',
        ),
    ]
